/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_openmax_OpenMaxActivity */

#ifndef _Included_com_example_openmax_OpenMaxActivity
#define _Included_com_example_openmax_OpenMaxActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    createStreamingMediaPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_openmax_OpenMaxActivity_createStreamingMediaPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    setPlayingStreamingMediaPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxActivity_setPlayingStreamingMediaPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxActivity_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    setSurface
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxActivity_setSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_openmax_OpenMaxActivity
 * Method:    rewindStreamingMediaPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxActivity_rewindStreamingMediaPlayer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
