/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testopensl_AudioTrackActivity */

#ifndef _Included_com_example_testopensl_AudioTrackActivity
#define _Included_com_example_testopensl_AudioTrackActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioTrackActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    createAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_testopensl_AudioTrackActivity_createAudioPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    setPlayingAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioTrackActivity_setPlayingAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    setVolumeAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioTrackActivity_setVolumeAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    setMutAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioTrackActivity_setMutAudioPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_testopensl_AudioTrackActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioTrackActivity_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
