/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_openmax_OpenMaxURIActivity */

#ifndef _Included_com_example_openmax_OpenMaxURIActivity
#define _Included_com_example_openmax_OpenMaxURIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxURIActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    createStreamingMediaPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_openmax_OpenMaxURIActivity_createStreamingMediaPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    setPlayingStreamingMediaPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxURIActivity_setPlayingStreamingMediaPlayer
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxURIActivity_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    setSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxURIActivity_setSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_openmax_OpenMaxURIActivity
 * Method:    rewindStreamingMediaPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_openmax_OpenMaxURIActivity_rewindStreamingMediaPlayer
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
